// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.0
// source: hashing.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HashingService_CheckHash_FullMethodName  = "/hashing.HashingService/CheckHash"
	HashingService_GetHash_FullMethodName    = "/hashing.HashingService/GetHash"
	HashingService_CreateHash_FullMethodName = "/hashing.HashingService/CreateHash"
)

// HashingServiceClient is the client API for HashingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashingServiceClient interface {
	CheckHash(ctx context.Context, in *CheckHashRequest, opts ...grpc.CallOption) (*CheckHashResponse, error)
	GetHash(ctx context.Context, in *GetHashRequest, opts ...grpc.CallOption) (*GetHashResponse, error)
	CreateHash(ctx context.Context, in *CreateHashRequest, opts ...grpc.CallOption) (*CreateHashResponse, error)
}

type hashingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashingServiceClient(cc grpc.ClientConnInterface) HashingServiceClient {
	return &hashingServiceClient{cc}
}

func (c *hashingServiceClient) CheckHash(ctx context.Context, in *CheckHashRequest, opts ...grpc.CallOption) (*CheckHashResponse, error) {
	out := new(CheckHashResponse)
	err := c.cc.Invoke(ctx, HashingService_CheckHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashingServiceClient) GetHash(ctx context.Context, in *GetHashRequest, opts ...grpc.CallOption) (*GetHashResponse, error) {
	out := new(GetHashResponse)
	err := c.cc.Invoke(ctx, HashingService_GetHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashingServiceClient) CreateHash(ctx context.Context, in *CreateHashRequest, opts ...grpc.CallOption) (*CreateHashResponse, error) {
	out := new(CreateHashResponse)
	err := c.cc.Invoke(ctx, HashingService_CreateHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashingServiceServer is the server API for HashingService service.
// All implementations must embed UnimplementedHashingServiceServer
// for forward compatibility
type HashingServiceServer interface {
	CheckHash(context.Context, *CheckHashRequest) (*CheckHashResponse, error)
	GetHash(context.Context, *GetHashRequest) (*GetHashResponse, error)
	CreateHash(context.Context, *CreateHashRequest) (*CreateHashResponse, error)
	mustEmbedUnimplementedHashingServiceServer()
}

// UnimplementedHashingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHashingServiceServer struct {
}

func (UnimplementedHashingServiceServer) CheckHash(context.Context, *CheckHashRequest) (*CheckHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHash not implemented")
}
func (UnimplementedHashingServiceServer) GetHash(context.Context, *GetHashRequest) (*GetHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHash not implemented")
}
func (UnimplementedHashingServiceServer) CreateHash(context.Context, *CreateHashRequest) (*CreateHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHash not implemented")
}
func (UnimplementedHashingServiceServer) mustEmbedUnimplementedHashingServiceServer() {}

// UnsafeHashingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashingServiceServer will
// result in compilation errors.
type UnsafeHashingServiceServer interface {
	mustEmbedUnimplementedHashingServiceServer()
}

func RegisterHashingServiceServer(s grpc.ServiceRegistrar, srv HashingServiceServer) {
	s.RegisterService(&HashingService_ServiceDesc, srv)
}

func _HashingService_CheckHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashingServiceServer).CheckHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashingService_CheckHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashingServiceServer).CheckHash(ctx, req.(*CheckHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashingService_GetHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashingServiceServer).GetHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashingService_GetHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashingServiceServer).GetHash(ctx, req.(*GetHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashingService_CreateHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashingServiceServer).CreateHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashingService_CreateHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashingServiceServer).CreateHash(ctx, req.(*CreateHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashingService_ServiceDesc is the grpc.ServiceDesc for HashingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashing.HashingService",
	HandlerType: (*HashingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHash",
			Handler:    _HashingService_CheckHash_Handler,
		},
		{
			MethodName: "GetHash",
			Handler:    _HashingService_GetHash_Handler,
		},
		{
			MethodName: "CreateHash",
			Handler:    _HashingService_CreateHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashing.proto",
}
